services:
  php-fpm:
    depends_on:
      - db
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: dev
    working_dir: /home/catter
    volumes:
      - .:/home/catter
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/php.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${FPM_PORT:-9000}:9000"
    environment:
      - XDEBUG_SESSION
      - XDEBUG_CONFIG
      - XDEBUG_MODE
      - APP_ENV
      - APP_SECRET
      - DATABASE_URL
      - MESSENGER_TRANSPORT_DSN

  db:
    image: mysql:8.0
    volumes:
      - "db-data:/var/lib/mysql"
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    hostname: "${MYSQL_HOST:-db}"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_NAME}"
    ports:
      - "${MYSQL_PORT}:3306"

volumes:
  db-data:
    external: true
    name: catter-db-data