services:
  nginx:
    depends_on:
      - php-fpm
    volumes:
      - ./public:/home/catter/public
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
    image: nginx:stable
    working_dir: /home/catter
    ports:
      - "${NGINX_PORT}:8000"
      
  adminer:
    depends_on:
      - db
    image: dockette/adminer:latest
    restart: always
    ports:
      - "${ADMINER_PORT}:80"